chore: update elastic/beats to c50e2cc4adfa (#134)
Update to elastic/beats@c50e2cc4adfa (9.1.4).

This required a patch to gopsutil to fix this build issue:

GOOS=js GOARCH=wasm go build -o ui/public/processors.wasm -ldflags "-X main.version=dev" ./internal/wasm
../../../go/pkg/mod/github.com/elastic/elastic-agent-system-metrics@v0.13.2/metric/system/cgroup/cgv1/cpuacct.go:32:29: undefined: cpu.ClocksPerSec

https://github.com/andrewkroh/gopsutil/commit/70d90208035207e88894b71675b820165547bf42